services:
  edge-tunnel:
    build: .
    container_name: edge-tunnel
    environment:
      - WG_HOST=edge.xoxoent.space
      - PORT=51821
      - WG_PORT=51820
      - UI_TRAFFIC_STATS=true
      # V15 Initialization
      - INIT_ENABLED=true
      - INIT_USERNAME=admin
      - INIT_PASSWORD=${ADMIN_PASSWORD}
      - INIT_HOST=edge.xoxoent.space
      - INIT_PORT=51820
      - INIT_DNS=1.1.1.1,1.0.0.1
    volumes:
      - ./data:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
    expose:
      - "51821"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - web_network

networks:
  web_network:
    external: true
